"""empty message

Revision ID: 9c4fb5265831
Revises: 4320c7a94e60
Create Date: 2021-04-22 21:25:27.388013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4fb5265831'
down_revision = '4320c7a94e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serie', sa.Column('backdrop', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serie', 'backdrop')
    # ### end Alembic commands ###
